name: quicksend
services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: quicksend_app
    volumes:
      - ./:/app/
    env_file:
      - .env
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.70.0.2

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: quicksend_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 172.70.0.3

  rabbitmq:
    image: rabbitmq:4.2-management-alpine
    container_name: quicksend_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      default:
        ipv4_address: 172.70.0.4

  db:
    image: postgres:17
    container_name: quicksend_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.70.0.5

  redis:
    image: redis:8.4.0
    container_name: quicksend_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      default:
        ipv4_address: 172.70.0.6

  seq:
    image: datalust/seq:2025.2
    container_name: quicksend_seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINUSERNAME: "${SEQ_FIRSTRUN_ADMINUSERNAME}"
      SEQ_FIRSTRUN_ADMINPASSWORD: "${SEQ_FIRSTRUN_ADMINPASSWORD}"
    ports:
      - "5431:80"
    volumes:
      - seq_data:/data
    networks:
      default:
        ipv4_address: 172.70.0.7

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true

volumes:
  redis_data:
  postgres_data:
  rabbitmq_data:
  seq_data:
